# Generated by Django 4.1.3 on 2024-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='country',
            field=models.CharField(choices=[('india', 'India'), ('pakistan', 'Pakistan'), ('bangladesh', 'Bangladesh'), ('srilanka', 'Sri Lanka'), ('china', 'China'), ('bhutan', 'Bhutan')], default='india', max_length=100),
            preserve_default=False,
        ),
    ]
